task_type: detection
dataset_category: coco
calibration_dataset:
  num_classes: 90
  num_frames: 25
  name: coco
  path: ./dependencies/datasets/coco
  split: val2017
  shuffle: true
  dataset_info: /data/files/a0508577/work/edgeai-algo/edgeai-benchmark/work_dirs/modelartifacts/AM68A/8bits/od-8220_onnxrt_coco_edgeai-mmdet_yolox_s_lite_640x640_20220221_model_onnx/dataset.yaml
input_dataset:
  num_classes: 90
  num_frames: 100
  name: coco
  path: ./dependencies/datasets/coco
  split: val2017
  shuffle: false
  dataset_info: /data/files/a0508577/work/edgeai-algo/edgeai-benchmark/work_dirs/modelartifacts/AM68A/8bits/od-8220_onnxrt_coco_edgeai-mmdet_yolox_s_lite_640x640_20220221_model_onnx/dataset.yaml
preprocess:
  resize: 640
  crop: 640
  data_layout: NCHW
  reverse_channels: true
  backend: cv2
  interpolation: null
  add_flip_image: false
  resize_with_pad:
  - true
  - corner
  pad_color:
  - 114
  - 114
  - 114
session:
  session_name: onnxrt
  work_dir: ./work_dirs/modelartifacts/AM68A/8bits
  target_machine: pc
  target_device: AM68A
  run_suffix: null
  tidl_offload: true
  input_optimization: true
  input_data_layout: NCHW
  input_mean: null
  input_scale: null
  run_dir_tree_depth: 3
  runtime_options:
    platform: J7
    version: 10.0.2
    tidl_tools_path: /data/files/a0508577/work/edgeai-algo/edgeai-benchmark/tools/AM68A/tidl_tools
    artifacts_folder: /data/files/a0508577/work/edgeai-algo/edgeai-benchmark/work_dirs/modelartifacts/AM68A/8bits/od-8220_onnxrt_coco_edgeai-mmdet_yolox_s_lite_640x640_20220221_model_onnx/artifacts
    tensor_bits: 8
    import: 'yes'
    accuracy_level: 1
    debug_level: 0
    inference_mode: 0
    advanced_options:high_resolution_optimization: 0
    advanced_options:pre_batchnorm_fold: 1
    advanced_options:calibration_frames: 12
    advanced_options:calibration_iterations: 12
    advanced_options:quantization_scale_type: 4
    advanced_options:activation_clipping: 1
    advanced_options:weight_clipping: 1
    advanced_options:bias_calibration: 1
    advanced_options:output_feature_16bit_names_list: 1033, 711, 712, 713, 727, 728,
      728, 743, 744, 745
    advanced_options:params_16bit_names_list: ''
    advanced_options:add_data_convert_ops: 3
    ti_internal_nc_flag: 83886080
    info:
      prequantized_model_type: 0
    object_detection:confidence_threshold: 0.3
    object_detection:top_k: 200
    object_detection:meta_arch_type: 6
    object_detection:meta_layers_names_list: /data/files/a0508577/work/edgeai-algo/edgeai-benchmark/work_dirs/modelartifacts/AM68A/8bits/od-8220_onnxrt_coco_edgeai-mmdet_yolox_s_lite_640x640_20220221_model_onnx/model/yolox_s_lite_640x640_20220221_model.prototxt
    advanced_options:quant_params_proto_path: /data/files/a0508577/work/edgeai-algo/edgeai-benchmark/work_dirs/modelartifacts/AM68A/8bits/od-8220_onnxrt_coco_edgeai-mmdet_yolox_s_lite_640x640_20220221_model_onnx/model/yolox_s_lite_640x640_20220221_model_qparams.prototxt
  model_path: /data/files/a0508577/work/edgeai-algo/edgeai-modelzoo/models/vision/detection/coco/edgeai-mmdet/yolox_s_lite_640x640_20220221_model.onnx
  tidl_tools_path: /data/files/a0508577/work/edgeai-algo/edgeai-benchmark/tools/AM68A/tidl_tools
  run_dir: /data/files/a0508577/work/edgeai-algo/edgeai-benchmark/work_dirs/modelartifacts/AM68A/8bits/od-8220_onnxrt_coco_edgeai-mmdet_yolox_s_lite_640x640_20220221_model_onnx
  num_tidl_subgraphs: 16
  model_id: od-8220
  model_type: null
  input_details:
  - name: inputNet_IN
    shape:
    - 1
    - 3
    - 640
    - 640
    type: tensor(uint8)
  output_details:
  - name: dets
    shape:
    - 200
    - 5
    type: tensor(float)
  - name: labels
    shape:
    - 200
    type: tensor(int64)
  num_inputs: 1
  extra_inputs: null
  tensor_bits: 8
  quant_params_proto_path: true
  supported_machines: null
  with_onnxsim: false
  shape_inference: true
  tidl_onnx_model_optimizer: false
  deny_list_from_start_end_node: null
  artifacts_folder: /data/files/a0508577/work/edgeai-algo/edgeai-benchmark/work_dirs/modelartifacts/AM68A/8bits/od-8220_onnxrt_coco_edgeai-mmdet_yolox_s_lite_640x640_20220221_model_onnx/artifacts
  model_folder: /data/files/a0508577/work/edgeai-algo/edgeai-benchmark/work_dirs/modelartifacts/AM68A/8bits/od-8220_onnxrt_coco_edgeai-mmdet_yolox_s_lite_640x640_20220221_model_onnx/model
  model_file: /data/files/a0508577/work/edgeai-algo/edgeai-benchmark/work_dirs/modelartifacts/AM68A/8bits/od-8220_onnxrt_coco_edgeai-mmdet_yolox_s_lite_640x640_20220221_model_onnx/model/yolox_s_lite_640x640_20220221_model.onnx
postprocess:
  detection_threshold: 0.3
  save_output: false
  formatter:
    src_indices:
    - 5
    - 4
    dst_indices:
    - 4
    - 5
    name: DetectionBoxSL2BoxLS
  resize_with_pad: true
  normalized_detections: false
  shuffle_indices: null
  squeeze_axis: null
  ignore_index: null
  logits_bbox_to_bbox_ls: false
metric:
  label_offset_pred:
    0: 1
    1: 2
    2: 3
    3: 4
    4: 5
    5: 6
    6: 7
    7: 8
    8: 9
    9: 10
    10: 11
    11: 13
    12: 14
    13: 15
    14: 16
    15: 17
    16: 18
    17: 19
    18: 20
    19: 21
    20: 22
    21: 23
    22: 24
    23: 25
    24: 27
    25: 28
    26: 31
    27: 32
    28: 33
    29: 34
    30: 35
    31: 36
    32: 37
    33: 38
    34: 39
    35: 40
    36: 41
    37: 42
    38: 43
    39: 44
    40: 46
    41: 47
    42: 48
    43: 49
    44: 50
    45: 51
    46: 52
    47: 53
    48: 54
    49: 55
    50: 56
    51: 57
    52: 58
    53: 59
    54: 60
    55: 61
    56: 62
    57: 63
    58: 64
    59: 65
    60: 67
    61: 70
    62: 72
    63: 73
    64: 74
    65: 75
    66: 76
    67: 77
    68: 78
    69: 79
    70: 80
    71: 81
    72: 82
    73: 84
    74: 85
    75: 86
    76: 87
    77: 88
    78: 89
    79: 90
    80: 91
model_info:
  metric_reference:
    accuracy_ap[.5:.95]%: 38.3
  model_shortlist: 10
  compact_name: yolox-s-lite-mmdet-coco-640x640
  shortlisted: true
  recommended: true
