metric:
  label_offset_pred:
    0: 1
    1: 2
    2: 3
    3: 4
    4: 5
    5: 6
    6: 7
    7: 8
    8: 9
    9: 10
    10: 11
    11: 13
    12: 14
    13: 15
    14: 16
    15: 17
    16: 18
    17: 19
    18: 20
    19: 21
    20: 22
    21: 23
    22: 24
    23: 25
    24: 27
    25: 28
    26: 31
    27: 32
    28: 33
    29: 34
    30: 35
    31: 36
    32: 37
    33: 38
    34: 39
    35: 40
    36: 41
    37: 42
    38: 43
    39: 44
    40: 46
    41: 47
    42: 48
    43: 49
    44: 50
    45: 51
    46: 52
    47: 53
    48: 54
    49: 55
    50: 56
    51: 57
    52: 58
    53: 59
    54: 60
    55: 61
    56: 62
    57: 63
    58: 64
    59: 65
    60: 67
    61: 70
    62: 72
    63: 73
    64: 74
    65: 75
    66: 76
    67: 77
    68: 78
    69: 79
    70: 80
    71: 81
    72: 82
    73: 84
    74: 85
    75: 86
    76: 87
    77: 88
    78: 89
    79: 90
    80: 91
postprocess:
  formatter:
    dst_indices:
    - 4
    - 5
    name: DetectionBoxSL2BoxLS
    src_indices:
    - 5
    - 4
  ignore_index: null
  logits_bbox_to_bbox_ls: false
  normalized_detections: false
  resize_with_pad: true
  shuffle_indices: null
  squeeze_axis: null
preprocess:
  add_flip_image: false
  crop: 640
  data_layout: NCHW
  pad_color:
  - 114
  - 114
  - 114
  resize: 640
  resize_with_pad:
  - true
  - corner
  reverse_channels: true
session:
  artifacts_folder: artifacts
  input_data_layout: NCHW
  input_details:
  - name: inputNet_IN
    shape:
    - 1
    - 3
    - 640
    - 640
    type: tensor(uint8)
  input_mean: null
  input_optimization: true
  input_scale: null
  model_folder: model
  model_path: model/yolox_s_lite_640x640_20220221_model.onnx
  output_details:
  - name: dets
    shape:
    - 200
    - 5
    type: tensor(float)
  - name: labels
    shape:
    - 200
    type: tensor(int64)
  run_dir: od-8220_onnxrt_coco_edgeai-mmdet_yolox_s_lite_640x640_20220221_model_onnx
  session_name: onnxrt
  target_device: AM68A
task_type: detection
